# Generated by Django 5.0.1 on 2024-02-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_videoitem_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charity_title', models.CharField(max_length=255)),
                ('charity_short_description', models.TextField()),
                ('charity_long_description', models.TextField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
