# Generated by Django 5.0.1 on 2024-02-16 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_charityitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoItem',
        ),
    ]
